using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

public partial class FrmBooking1 : System.Web.UI.Page
{
    public string str = "data source=.;Database = CourierService;Integrated Security=true";
    protected void cboExpMonth_SelectedIndexChanged(object sender, EventArgs e)
    {

    }

    public void Submit()
    {
        SqlConnection con = new SqlConnection(str);
        try
        {

            SqlCommand cmd = new SqlCommand("insert into  Booking ( Booked_by_UserId,Booked_Item,Booked_Weight,OfficeId_Recv,OfficeId_Send,ExpReceiveDate,ExpReceiveMonth,ExpReceiveYear,ActualReceiveDate,ActualReceiveMonth,ActualReceiveYear,Origin_CityId,Destination_CityId,Whether)values(@Booked_by_UserId,@Booked_Item,@Booked_Weight,@OfficeId_Recv,@OfficeId_Send,@ExpReceiveDate,@ExpReceiveMonth,@ExpReceiveYear,@ActualReceiveDate,@ActualReceiveMonth,@ActualReceiveYear,@Origin_CityId,@Destination_CityId,@Whether)", con);

            cmd.Parameters.Add(new SqlParameter("@Booked_by_UserId", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@Booked_Item", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@Booked_Weight", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@OfficeId_Recv", SqlDbType.BigInt));
            cmd.Parameters.Add(new SqlParameter("@OfficeId_Send", SqlDbType.BigInt));
            cmd.Parameters.Add(new SqlParameter("@ExpReceiveDate", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@ExpReceiveMonth", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@ExpReceiveYear", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@ActualReceiveDate", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@ActualReceiveMonth", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@ActualReceiveYear", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@Origin_CityId", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@Destination_CityId", SqlDbType.NVarChar, 50));
            cmd.Parameters.Add(new SqlParameter("@Whether", SqlDbType.NVarChar, 50));


            cmd.Parameters["@Booked_by_UserId"].Value = txtUserId.Text;
            cmd.Parameters["@Booked_Item"].Value = txtItem.Text;
            cmd.Parameters["@Booked_Weight"].Value = txtWeigth.Text;
            cmd.Parameters["@OfficeId_Recv"].Value = int.Parse(cboOfficeR.SelectedValue);
            cmd.Parameters["@OfficeId_Send"].Value = int.Parse(cboOfficeS.SelectedValue);
            cmd.Parameters["@ExpReceiveDate"].Value = cboDateExp.Text;

            cmd.Parameters["@ExpReceiveMonth"].Value = cboExpMonth.Text;

            cmd.Parameters["@ExpReceiveYear"].Value = cboExpYear.Text;
            cmd.Parameters["@ActualReceiveDate"].Value = cboRecvDate.Text;
            cmd.Parameters["@ActualReceiveMonth"].Value = cboRevMonth.Text;
            cmd.Parameters["@ActualReceiveYear"].Value = cboRecvYear.Text;
            cmd.Parameters["@Origin_CityId"].Value = int.Parse(cboOrigin.SelectedValue);

            cmd.Parameters["@Destination_CityId"].Value = int.Parse(cboDestination.SelectedValue);

            cmd.Parameters["@Whether"].Value = cboWhether.SelectedItem.Text;






            con.Open();
            cmd.ExecuteNonQuery();
            Label1.Text = "Booked Thankyou !";
            //Response.Redirect("http://localhost:1088/CargoSevice/FrmBooking.aspx");

        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
        finally
        {
            con.Close();
        }


        // to fetch Booking no. recently generated by adding Booking

        try
        {

            SqlCommand cmd1 = new SqlCommand("select max([ID]) from Booking", con);
            con.Open();
            object BookingId = cmd1.ExecuteScalar();

            Label1.Text = " This Item is Booked ! Booking No is  " + BookingId.ToString();




            //Response.Redirect("http://localhost:1088/CargoSevice/FrmBooking.aspx");

        }
        catch (Exception ex)
        {
            Label1.Text = ex.Message;
        }
        finally
        {
            con.Close();
        }


    }

    protected void btnUpdate_Click(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection(str);

        int flag = 0;

        try
        {
            SqlCommand cmd = new SqlCommand("select UserId,OfOffice from  ManagerDetail where UserID = '" + txtUserId.Text + "'", con);
            con.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.Read())
            {
                //OfficeId = dr[1].ToString();
                flag = 1;
            }
            else
            {
                flag = 0;

            }


        }
        catch (Exception ex)
        {


            Label1.Text = ex.Message;
        }

        finally
        {
            con.Close();
        }

        if (flag == 0)
        {
            Label1.Text = "This User Id does'nt exit.Please enter the valid UserId";
        }
        else
        {
            Submit();
        }


    }
    protected void RadioButtonList1_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void BtnSearch_Click(object sender, EventArgs e)
    {

    }
}
